<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Pdf.Domain\Pdf.Domain.csproj" />
    <ProjectReference Include="..\Pdf.Application\Pdf.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2024.10.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
